# Custom Language File for Launcher Customizer

[ejs.app]
title = "HuskaLauncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Huskago/HuskaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/Huskago/HuskaLauncher"
supportLink = "https://github.com/Huskago/HuskaLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO HUSKAWORLD"
welcomeDescription = "Bienvenue dans le monde de Huskago, un monde de magie et de merveilles. Vous pouvez explorer le monde, faire des quêtes, construire votre propre maison, faire du commerce, et bien plus encore. HuskaWorld est un monde de possibilités infinies. Où vous pourrez installer les différentes modpacks facilement et rapidement."
welcomeDescCTA = "Vous êtes à quelques clics de HuskaWorld."
